import { Framework } from './types';

export const FRAMEWORK_META: Record<Framework, { icon: string; color: string }> = {
  [Framework.AUTO]: { icon: '⚡', color: 'text-cyber-success' },
  [Framework.KERNEL]: { icon: '🛡️', color: 'text-cyber-primary' },
  [Framework.COSTAR]: { icon: '✨', color: 'text-cyber-secondary' },
  [Framework.RISEN]: { icon: '🤖', color: 'text-cyber-accent' },
  [Framework.RTF]: { icon: '📋', color: 'text-blue-400' },
  [Framework.BAB]: { icon: '🌉', color: 'text-pink-500' },
  [Framework.TAG]: { icon: '🎯', color: 'text-emerald-400' },
  [Framework.CARE]: { icon: '💎', color: 'text-amber-400' },
  [Framework.REACT]: { icon: '🧩', color: 'text-sky-400' },
  [Framework.CHAIN]: { icon: '⛓️', color: 'text-violet-400' },
  [Framework.TREE]: { icon: '🌳', color: 'text-lime-400' },
  [Framework.REWOO]: { icon: '🧠', color: 'text-fuchsia-400' },
  [Framework.DSP]: { icon: '📐', color: 'text-cyan-300' },
  [Framework.SELFREFINE]: { icon: '♻️', color: 'text-teal-400' },
  [Framework.CRITIC]: { icon: '🧪', color: 'text-rose-400' },
  [Framework.SCENARIO]: { icon: '🗺️', color: 'text-orange-400' },
  [Framework.OODA]: { icon: '🔄', color: 'text-indigo-400' },
  [Framework.REDTEAM]: { icon: '🚨', color: 'text-red-400' },
  [Framework.SOCRATIC]: { icon: '❓', color: 'text-yellow-300' },
  [Framework.SWOT]: { icon: '📊', color: 'text-blue-300' },
  [Framework.FIVEWHYS]: { icon: '🔍', color: 'text-amber-300' },
  [Framework.MECE]: { icon: '🧮', color: 'text-green-300' },
  [Framework.SCAMPER]: { icon: '💡', color: 'text-orange-300' },
  [Framework.PDCA]: { icon: '🔁', color: 'text-cyan-400' },
  [Framework.STAR]: { icon: '⭐', color: 'text-yellow-400' },
  [Framework.SMART]: { icon: '🎯', color: 'text-emerald-300' },
  [Framework.DIALECTIC]: { icon: '⚖️', color: 'text-purple-300' },
  [Framework.STEPBACK]: { icon: '🪜', color: 'text-slate-300' },
  [Framework.ANALOGICAL]: { icon: '🔀', color: 'text-sky-300' },
  [Framework.MORPHOLOGICAL]: { icon: '🧊', color: 'text-zinc-300' },
  [Framework.DELPHI]: { icon: '🏛️', color: 'text-stone-300' },
  [Framework.SIX_HATS]: { icon: '🎩', color: 'text-yellow-200' },
  [Framework.TRIZ]: { icon: '🔧', color: 'text-gray-300' },
  [Framework.PESTEL]: { icon: '🌐', color: 'text-blue-200' },
  [Framework.PORTER]: { icon: '🏢', color: 'text-neutral-300' },
  [Framework.LEAN]: { icon: '🪶', color: 'text-green-200' },
  [Framework.AGILE]: { icon: '🏃', color: 'text-blue-400' },
  [Framework.FIRST_PRINCIPLES]: { icon: '🔬', color: 'text-violet-300' },
  [Framework.INVERSION]: { icon: '🔃', color: 'text-red-300' },
  [Framework.FUTURES_WHEEL]: { icon: '🎡', color: 'text-pink-300' },
  [Framework.BACKCASTING]: { icon: '⏪', color: 'text-indigo-300' },
  [Framework.KANO]: { icon: '📈', color: 'text-emerald-200' },
  [Framework.JTBD]: { icon: '🛠️', color: 'text-orange-200' },
  [Framework.DESIGN_THINKING]: { icon: '💭', color: 'text-pink-400' },
  [Framework.SYSTEMS_THINKING]: { icon: '🕸️', color: 'text-teal-300' },
  [Framework.GAME_THEORY]: { icon: '♟️', color: 'text-amber-200' },
  [Framework.BAYESIAN]: { icon: '📉', color: 'text-cyan-200' },
  [Framework.META_PROMPT]: { icon: '🪞', color: 'text-fuchsia-300' },
  [Framework.LATERAL]: { icon: '↗️', color: 'text-lime-300' },
  [Framework.CATWOE]: { icon: '🔎', color: 'text-rose-300' },
  [Framework.DECISION_MATRIX]: { icon: '📋', color: 'text-slate-400' },
  [Framework.MIND_MAP]: { icon: '🗂️', color: 'text-purple-200' },
  [Framework.RAPID]: { icon: '⚡', color: 'text-yellow-500' },
  [Framework.MOSCOW]: { icon: '🏷️', color: 'text-green-400' },
  [Framework.OKR]: { icon: '🎯', color: 'text-red-200' },
  [Framework.HYPOTHESIS]: { icon: '🧪', color: 'text-violet-200' },
  [Framework.PREMORTEM]: { icon: '💀', color: 'text-gray-400' },
};

export const DOMAIN_META: Record<string, { icon: string }> = {
  'auto': { icon: '⚡' },
  'general': { icon: '🧠' },
  'ui-design': { icon: '🎨' },
  'architecture': { icon: '🏗️' },
  'frontend': { icon: '💻' },
  'backend': { icon: '⚙️' },
  'analysis': { icon: '📊' },
  'testing': { icon: '🔒' },
  'image-video': { icon: '🎬' },
  'data-engineering': { icon: '🗄️' },
  'ml-ai': { icon: '🤖' },
  'devops-sre': { icon: '☁️' },
  'mobile-dev': { icon: '📱' },
  'game-dev': { icon: '🕹️' },
  'fintech': { icon: '💳' },
  'healthcare': { icon: '🩺' },
  'legal-compliance': { icon: '⚖️' },
  'ecommerce-growth': { icon: '🛒' },
  'education-edtech': { icon: '🎓' },
  'blockchain-web3': { icon: '🔗' },
  'cybersecurity': { icon: '🛡️' },
  'iot-embedded': { icon: '📡' },
  'content-marketing': { icon: '✍️' },
  'hr-talent': { icon: '👥' },
  'supply-chain': { icon: '🚚' },
  'sustainability': { icon: '🌱' },
  'robotics-automation': { icon: '🤖' },
  'media-entertainment': { icon: '🎭' },
  'research-academia': { icon: '🔬' },
  'saas-product': { icon: '🚀' },
  'api-integration': { icon: '🔌' },
  'cloud-native': { icon: '☁️' },
  'nlp-llm': { icon: '💬' },
  'computer-vision': { icon: '👁️' },
  'audio-speech': { icon: '🎙️' },
  'database-admin': { icon: '🗃️' },
  'networking': { icon: '🌐' },
  'real-estate': { icon: '🏠' },
  'agriculture': { icon: '🌾' },
  'energy-cleantech': { icon: '⚡' },
  'automotive': { icon: '🚗' },
  'aerospace-defense': { icon: '✈️' },
  'insurance': { icon: '🛡️' },
  'travel-hospitality': { icon: '🏨' },
  'food-beverage': { icon: '🍽️' },
  'fashion-retail': { icon: '👗' },
  'sports-fitness': { icon: '🏋️' },
  'social-impact': { icon: '🤝' },
  'government': { icon: '🏛️' },
  'telecom': { icon: '📶' },
  'construction': { icon: '🏗️' },
  'mining-resources': { icon: '⛏️' },
  'pharmaceutical': { icon: '💊' },
  'mental-health': { icon: '🧘' },
  'accessibility': { icon: '♿' },
  'localization-i18n': { icon: '🌍' },
  'developer-experience': { icon: '🧑‍💻' },
  'data-privacy': { icon: '🔐' },
  'conversational-ai': { icon: '💬' },
};

export const DOMAIN_IDS = Object.keys(DOMAIN_META);
